export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-money-check"></i>
export const incomes = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const logout = <i className="fa-solid fa-right-from-bracket"></i>
export const settings = <i className="fa-solid fa-gear"></i>
export const calendar = <i className="fa-solid fa-calendar-days"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const comment = < i className="fa-solid fa-comment"></i>
export const list = <i className="fa-solid fa-list"></i>
export const users = <i className="fa-solid fa-users"></i>
export const dumbell = <i className="fa-solid fa-dumbbell"></i>
export const swim = <i className="fa-solid fa-person-swimming"></i>
export const badminton = <i className="fa-solid fa-badminton"></i>
export const pool = <i className="fa-solid fa-pool-8-ball"></i>
export const pharmacy = <i className="fa-solid fa-house-medical"></i>
export const booking = <i className="fa-solid fa-book"></i>
export const rupees = <i className="fa-solid fa-rupee-sign"></i>
export const bolt = <i className="fa-solid fa-bolt"></i>
export const water = <i className="fa-solid fa-glass-water-droplet"></i>
export const wrench = <i className="fa-solid fa-wrench"></i>
export const maintain = <i className="fa-solid fa-paint-roller"></i>
export const broom = <i className="fa-solid fa-broom"></i>
export const salary = <i className="fa-solid fa-hand-holding-dollar"></i>
export const pending = <i className="fa-solid fa-hourglass-end"></i>
export const done = <i class="fa-solid fa-circle-check"></i>