export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-money-check"></i>
export const incomes = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const logout = <i className="fa-solid fa-right-from-bracket"></i>
export const settings = <i className="fa-solid fa-gear"></i>
export const calendar = <i className="fa-solid fa-calendar-days"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const comment = < i className="fa-solid fa-comment"></i>
export const list = <i className="fa-solid fa-list"></i>
export const users = <i className="fa-solid fa-users"></i>
export const dumbell = <i class="fa-solid fa-dumbbell"></i>
export const swim = <i class="fa-solid fa-person-swimming"></i>
export const badminton = <i class="fa-solid fa-badminton"></i>
export const pool = <i class="fa-solid fa-pool-8-ball"></i>
export const pharmacy = <i class="fa-solid fa-house-medical"></i>
export const booking = <i class="fa-solid fa-book"></i>